Improve healthcheck
supabase/pg_graphql pull request #10
Opened 2021-12-04 00:30 UTC by utamori

## What kind of change does this PR introduce?

Modest improvements to docker-compose

## What is the current behavior?

`docker-compose.yaml`'s `depends_on` does not depend on the success of the health check.

https://github.com/peter-evans/docker-compose-healthcheck
https://github.com/compose-spec/compose-spec/blob/e8db8022c0b2e3d5eb007d629ff684cbe49a17a4/spec.md#long-syntax-1

## What is the new behavior?

We can make it dependent on the success of the health check by writing the following

```yml
    depends_on:
      db:
        condition: service_healthy
```

## Additional context

`condition: service_healthy` waits for the container to start. This is the same as if we had not written any condition.

In the compose spec, the version field is not required

2021-12-04 17:55 UTC, olirice commented
With the docker-compose update I'm getting 
```
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services: 'graphiql'
```

- docker-compose version 1.25.4, build 8d51620a
- ubuntu 20.04

A health check would be great but please do not adjust the indentation. We have a precommit hook to check that the formatting is valid [here](https://github.com/supabase/pg_graphql/blob/master/.pre-commit-config.yaml#L7)

2021-12-04 18:18 UTC, olirice requested changes
With the docker-compose update I'm getting

```
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services: 'graphiql'
```

- docker-compose version 1.25.4, build 8d51620a
- ubuntu 20.04


A health check would be great but please do not adjust the indentation. We have a precommit hook to check that the formatting is valid here

2021-12-06 01:52 UTC, utamori commented
I've turned the Intend back on.
Pre-commit is now also enabled.

Sorry. Implementation according to `Compose Spec` seems to be valid from Docker Compose v1.27.0+

> These topics describe the Docker Compose implementation of the Compose format. Docker Compose 1.27.0+ implements the format defined by the Compose Specification. Previous Docker Compose versions have support for several Compose file formats – 2, 2.x, and 3.x. The Compose specification is a unified 2.x and 3.x file format, aggregating properties across these formats.

https://docs.docker.com/compose/compose-file/

It also works with the `docker compose` command integrated into the `docker CLI`.

```
docker compose up
```
https://docs.docker.com/engine/reference/commandline/compose/

2021-12-06 12:07 UTC, olirice commented
@utamori thank you for the PR and the update. I checked the release date of docker-compose 1.27 and it was 2020-12

while we don't want to get in the habit of supporting outdated software, the main purpose of that docker-compose file is to power the quickstart guide. I'm hesitant to use newer syntax that will break on older docker installs during users' first experiences with this project

we can (and should) revisit this once the syntax is supported by a larger portion of the docker-compose install base. closing PR for now

thanks again!

2021-12-06 12:07 UTC, closed without merging